/**
 * よく使う単語・表現。
 *
 * 数字と違って生成できないので、ここに直接並べる。話題ごとに分けてあるのは
 * 選択肢を作るときに「同じ話題の中から」誤答を採るため。ciao の誤答が
 * portiere だと、意味を知らなくても消去法で当たってしまう。
 *
 * イタリア語側には冠詞をつけてある。名詞の性はまとめて覚えるほうが早いし、
 * 実際に口に出すときも冠詞ごと出てくるほうが使える。
 *
 * note は「日本語訳だけでは落ちない情報」があるときだけ書く。
 * 使い分け（scusa / scusi）、習慣（cappuccino は朝だけ）、決まった返し方など。
 *
 * 同じ話題の中では it も ja も重複させないこと。訳が重なると
 * 「正解が2つある問題」ができてしまう（テストで検査している）。
 */

export const TOPICS = [
  {
    id: 'saluti',
    ja: 'あいさつ',
    hint: 'ciao / grazie',
    entries: [
      // 出会いと別れ
      { it: 'ciao', ja: 'やあ、じゃあね', note: '親しい相手に。会うときも別れるときも使う' },
      { it: 'salve', ja: 'どうも', note: 'ciao より丁寧で buongiorno より軽い' },
      { it: 'buongiorno', ja: 'おはよう、こんにちは' },
      { it: 'buonasera', ja: 'こんばんは', note: '夕方から。会ったときのあいさつ' },
      { it: 'buonanotte', ja: 'おやすみ', note: '別れ際か寝る前だけ。出会いには使わない' },
      { it: 'arrivederci', ja: 'さようなら' },
      { it: 'arrivederla', ja: 'さようなら（丁寧）', note: '目上の人ひとりに' },
      { it: 'a presto', ja: 'またすぐに' },
      { it: 'a domani', ja: 'また明日' },
      { it: 'a dopo', ja: 'またあとで' },
      { it: 'ci vediamo', ja: 'また会おうね' },
      { it: 'ci sentiamo', ja: 'また連絡するね', note: '電話やメッセージで' },
      { it: 'benvenuto', ja: 'ようこそ' },

      // 調子をたずねる
      { it: 'come stai?', ja: '元気？', note: '親しい相手に。丁寧には come sta?' },
      { it: 'come sta?', ja: 'お元気ですか', note: '目上・初対面に' },
      { it: 'come va?', ja: '調子どう？' },
      { it: 'tutto bene?', ja: '大丈夫？' },
      { it: 'sto bene', ja: '元気です' },
      { it: 'benissimo', ja: 'とても元気' },
      { it: "non c'è male", ja: 'まあまあです' },
      { it: 'così così', ja: 'ぼちぼち' },
      { it: 'e tu?', ja: '君は？' },
      { it: 'e Lei?', ja: 'あなたは？', note: '丁寧に聞き返すとき' },

      // 自己紹介
      { it: 'piacere', ja: 'はじめまして' },
      { it: 'molto lieto', ja: 'お会いできて光栄です' },
      { it: 'come ti chiami?', ja: '名前は？' },
      { it: 'mi chiamo', ja: '私の名前は' },
      { it: 'di dove sei?', ja: 'どこの出身？' },
      { it: 'sono giapponese', ja: '日本人です' },

      // 礼と詫び
      { it: 'per favore', ja: 'お願いします', note: '同じ意味で per piacere とも言う' },
      { it: 'grazie', ja: 'ありがとう' },
      { it: 'grazie mille', ja: 'どうもありがとう' },
      { it: 'grazie di tutto', ja: 'いろいろありがとう' },
      { it: 'prego', ja: 'どういたしまして', note: '「どうぞ」の意味でも使う' },
      { it: 'di niente', ja: 'とんでもない' },
      { it: 'figurati', ja: '気にしないで' },
      { it: 'scusa', ja: 'ごめん', note: '親しい相手に。丁寧には scusi' },
      { it: 'scusi', ja: 'すみません', note: '知らない人に呼びかけるときも' },
      { it: 'mi dispiace', ja: '残念です', note: '気の毒に思うときの言い方。軽い謝罪にも' },
      { it: 'permesso', ja: '失礼します', note: '人の前を通るとき、部屋に入るとき' },
      { it: 'non ti preoccupare', ja: '心配しないで' },

      // 聞き返す・分からない
      { it: 'non capisco', ja: '分かりません' },
      { it: 'non lo so', ja: '知りません' },
      { it: 'come?', ja: 'え？', note: '聞き取れなかったときの聞き返し' },
      { it: 'puoi ripetere?', ja: 'もう一度言って' },
      { it: 'più lentamente', ja: 'もっとゆっくり' },
      { it: 'come si dice?', ja: '何と言いますか' },
      { it: 'che cosa significa?', ja: 'どういう意味ですか' },
      { it: 'parli inglese?', ja: '英語を話せますか' },

      // 返事
      { it: 'va bene', ja: 'いいですよ' },
      { it: "d'accordo", ja: '賛成です' },
      { it: 'certo', ja: 'もちろん' },
      { it: 'volentieri', ja: '喜んで' },
      { it: 'purtroppo', ja: '残念ながら' },
      { it: 'forse', ja: 'たぶん' },
      { it: 'meno male', ja: 'よかった' },
      { it: 'che peccato!', ja: '残念！' },
      { it: 'pronto?', ja: 'もしもし', note: '電話に出るとき' },
      { it: 'si accomodi', ja: 'どうぞお掛けください' },

      // 決まり文句
      { it: 'buon appetito', ja: 'めしあがれ', note: '食事を始める人にかける言葉' },
      { it: 'auguri', ja: 'おめでとう' },
      { it: 'congratulazioni', ja: '合格おめでとう', note: '成果をあげた人に' },
      { it: 'in bocca al lupo', ja: 'がんばって', note: '返しは crepi（il lupo）' },
      { it: 'buona giornata', ja: 'よい一日を' },
      { it: 'buona serata', ja: 'よい夜を' },
      { it: 'buon fine settimana', ja: 'よい週末を' },
      { it: 'buon viaggio', ja: 'よい旅を' },
      { it: 'buon lavoro', ja: '仕事がんばって' },
      { it: 'buone vacanze', ja: 'よい休暇を' },
      { it: 'buon compleanno', ja: '誕生日おめでとう' },
      { it: 'buon Natale', ja: 'メリークリスマス' },
      { it: 'buon anno', ja: 'あけましておめでとう' },
      { it: 'salute!', ja: 'お大事に', note: 'くしゃみをした人にかける' },
    ],
  },

  {
    id: 'bar',
    ja: 'バール・食事',
    hint: 'caffè / il conto',
    entries: [
      // バールで
      { it: 'un caffè', ja: 'エスプレッソ', note: 'イタリアで caffè といえばエスプレッソ' },
      { it: 'un cappuccino', ja: 'カプチーノ', note: '朝に飲むもの。食後には頼まない' },
      { it: 'un caffè macchiato', ja: 'マキアート', note: 'エスプレッソに少しミルク' },
      { it: 'un latte macchiato', ja: 'ラテマキアート', note: 'ミルクに少しコーヒー' },
      { it: 'un caffè corretto', ja: 'お酒入りコーヒー' },
      { it: 'un cornetto', ja: 'クロワッサン' },
      { it: 'una brioche', ja: '菓子パン' },
      { it: 'al banco', ja: 'カウンターで', note: '座って飲むより安い' },
      { it: 'al tavolo', ja: 'テーブルで' },
      { it: 'lo scontrino', ja: 'レシート', note: 'バールでは先に払ってレシートを見せる' },
      { it: 'da portare via', ja: '持ち帰りで' },

      // 注文と会計
      { it: 'vorrei', ja: '〜が欲しいのですが', note: 'voglio より丁寧。注文はこれで' },
      { it: 'un tavolo per due', ja: '2人用のテーブル' },
      { it: 'il menù', ja: 'メニュー' },
      { it: 'la carta dei vini', ja: 'ワインリスト' },
      { it: 'il conto', ja: 'お会計' },
      { it: 'il coperto', ja: '席料', note: '一人あたりにかかる。伝票に載る' },
      { it: 'la mancia', ja: 'チップ' },
      { it: 'il cameriere', ja: 'ウェイター' },
      { it: 'sono vegetariano', ja: 'ベジタリアンです' },
      { it: 'senza glutine', ja: 'グルテンなし' },
      { it: 'è piccante?', ja: '辛いですか' },
      { it: 'basta così', ja: 'これで十分です' },

      // コースの構成
      { it: "l'antipasto", ja: '前菜' },
      { it: 'il primo', ja: '第一の皿', note: 'パスタ・リゾットなど' },
      { it: 'il secondo', ja: '第二の皿', note: '肉か魚。つけ合わせは別に頼む' },
      { it: 'il contorno', ja: 'つけ合わせ' },
      { it: 'il dolce', ja: 'デザート' },
      { it: 'la colazione', ja: '朝食' },
      { it: 'il pranzo', ja: '昼食' },
      { it: 'la cena', ja: '夕食' },

      // 飲みもの
      { it: 'acqua naturale', ja: '炭酸なしの水' },
      { it: 'acqua frizzante', ja: '炭酸水' },
      { it: 'il vino rosso', ja: '赤ワイン' },
      { it: 'il vino bianco', ja: '白ワイン' },
      { it: 'il vino della casa', ja: 'ハウスワイン' },
      { it: 'lo spumante', ja: 'スパークリングワイン' },
      { it: 'la birra', ja: 'ビール' },
      { it: 'il latte', ja: '牛乳' },
      { it: 'cin cin', ja: '乾杯' },

      // 食べもの
      { it: 'il pane', ja: 'パン' },
      { it: 'la pasta', ja: 'パスタ' },
      { it: 'gli spaghetti', ja: 'スパゲッティ' },
      { it: 'la pizza', ja: 'ピザ' },
      { it: 'il risotto', ja: 'リゾット' },
      { it: 'la zuppa', ja: 'スープ' },
      { it: 'il riso', ja: '米' },
      { it: 'la carne', ja: '肉' },
      { it: 'il pesce', ja: '魚' },
      { it: 'il pollo', ja: '鶏肉' },
      { it: 'il manzo', ja: '牛肉' },
      { it: 'il maiale', ja: '豚肉' },
      { it: 'il prosciutto', ja: '生ハム' },
      { it: 'il formaggio', ja: 'チーズ' },
      { it: 'la verdura', ja: '野菜' },
      { it: "l'insalata", ja: 'サラダ' },
      { it: 'la frutta', ja: '果物' },
      { it: "l'uovo", ja: '卵' },
      { it: 'il gelato', ja: 'ジェラート' },

      // 調味料と食器
      { it: 'il sale', ja: '塩' },
      { it: 'il pepe', ja: 'こしょう' },
      { it: "l'olio", ja: 'オリーブオイル' },
      { it: "l'aceto", ja: '酢' },
      { it: 'il burro', ja: 'バター' },
      { it: 'lo zucchero', ja: '砂糖' },
      { it: 'il cucchiaio', ja: 'スプーン' },
      { it: 'la forchetta', ja: 'フォーク' },
      { it: 'il coltello', ja: 'ナイフ' },
      { it: 'il bicchiere', ja: 'コップ' },
      { it: 'la tazza', ja: 'カップ' },
      { it: 'il tovagliolo', ja: 'ナプキン' },

      // 感想
      { it: 'ho fame', ja: 'お腹がすいた' },
      { it: 'ho sete', ja: 'のどが渇いた' },
      { it: 'buonissimo', ja: 'とてもおいしい' },
    ],
  },

  {
    id: 'treno',
    ja: '電車・移動',
    hint: 'il binario / in ritardo',
    entries: [
      // 駅と切符
      { it: 'il treno', ja: '電車' },
      { it: 'la stazione', ja: '駅' },
      { it: 'il binario', ja: '〜番線', note: 'binario cinque のように番号をつけて言う' },
      { it: 'il biglietto', ja: '切符' },
      { it: 'la biglietteria', ja: '切符売り場' },
      { it: 'convalidare', ja: '（切符を）刻印する', note: '乗る前に刻印しないと罰金' },
      { it: 'andata e ritorno', ja: '往復' },
      { it: 'solo andata', ja: '片道' },
      { it: 'prenotare', ja: '予約する' },
      { it: 'il tabellone', ja: '発車案内板' },
      { it: "la sala d'attesa", ja: '待合室' },
      { it: 'il deposito bagagli', ja: '荷物預かり所' },

      // 乗り降り
      { it: 'la coincidenza', ja: '乗り換え' },
      { it: 'salire', ja: '乗る' },
      { it: 'scendere', ja: '降りる' },
      { it: 'il posto', ja: '席' },
      { it: 'la carrozza', ja: '車両' },
      { it: 'la fermata', ja: '停留所' },
      { it: 'il capolinea', ja: '終点' },
      { it: 'il controllore', ja: '車掌' },

      // 時間と乱れ
      { it: 'in ritardo', ja: '遅れて' },
      { it: 'in orario', ja: '定刻で' },
      { it: 'il ritardo', ja: '遅延' },
      { it: 'lo sciopero', ja: 'ストライキ', note: '交通機関では珍しくない' },
      { it: 'la partenza', ja: '出発' },
      { it: "l'arrivo", ja: '到着' },
      { it: 'a che ora parte?', ja: '何時発ですか' },
      { it: 'a che ora arriva?', ja: '何時着ですか' },
      { it: 'quanto ci vuole?', ja: 'どのくらいかかりますか' },

      // 乗りもの
      { it: 'il regionale', ja: '各駅停車', note: '速いのは Frecciarossa など' },
      { it: 'la metropolitana', ja: '地下鉄' },
      { it: "l'autobus", ja: 'バス' },
      { it: 'il pullman', ja: '長距離バス' },
      { it: 'il taxi', ja: 'タクシー' },
      { it: "l'aereo", ja: '飛行機' },
      { it: "l'aeroporto", ja: '空港' },
      { it: 'il traghetto', ja: 'フェリー' },
      { it: 'la nave', ja: '船' },
      { it: 'la bicicletta', ja: '自転車' },
      { it: 'la macchina', ja: '車' },
      { it: 'a piedi', ja: '徒歩で' },

      // 荷物と持ちもの
      { it: 'il bagaglio', ja: '荷物' },
      { it: 'la valigia', ja: 'スーツケース' },
      { it: 'lo zaino', ja: 'リュック' },
      { it: 'il passaporto', ja: 'パスポート' },
      { it: 'la patente', ja: '運転免許証' },
      { it: 'la mappa', ja: '地図' },

      // 建物のなか
      { it: "l'uscita", ja: '出口' },
      { it: "l'entrata", ja: '入口' },
      { it: 'il sottopassaggio', ja: '地下通路' },
      { it: 'la scala mobile', ja: 'エスカレーター' },
      { it: "l'ascensore", ja: 'エレベーター' },
      { it: 'il parcheggio', ja: '駐車場' },
      { it: 'la benzina', ja: 'ガソリン' },

      // 道をたずねる
      { it: "dov'è?", ja: 'どこですか' },
      { it: 'quanto costa?', ja: 'いくらですか' },
      { it: 'come si arriva?', ja: 'どうやって行きますか' },
      { it: 'mi sono perso', ja: '道に迷いました' },
      { it: 'a destra', ja: '右に' },
      { it: 'a sinistra', ja: '左に' },
      { it: 'sempre dritto', ja: 'まっすぐ' },
      { it: 'vicino', ja: '近い' },
      { it: 'lontano', ja: '遠い' },
      { it: 'qui', ja: 'ここ' },
      { it: 'là', ja: 'あそこ' },
      { it: "l'angolo", ja: '角' },
      { it: 'il semaforo', ja: '信号' },
      { it: 'la piazza', ja: '広場' },
      { it: 'la via', ja: '通り' },
      { it: 'il ponte', ja: '橋' },
      { it: 'il centro', ja: '中心街' },
      { it: 'la periferia', ja: '郊外' },
      { it: "l'albergo", ja: 'ホテル' },
      { it: 'la camera', ja: '部屋' },
    ],
  },

  {
    id: 'negozio',
    ja: '買い物',
    hint: "quant'è? / lo sconto",
    entries: [
      // 店
      { it: 'il negozio', ja: '店' },
      { it: 'il supermercato', ja: 'スーパー' },
      { it: 'il mercato', ja: '市場' },
      { it: 'il centro commerciale', ja: 'ショッピングセンター' },
      { it: 'la panetteria', ja: 'パン屋' },
      { it: 'la pasticceria', ja: 'ケーキ屋' },
      { it: 'la macelleria', ja: '肉屋' },
      { it: 'la pescheria', ja: '魚屋' },
      { it: 'la farmacia', ja: '薬局' },
      { it: 'il tabaccaio', ja: 'タバコ屋', note: '切手やバスの切符もここで買える' },
      { it: "l'edicola", ja: '新聞スタンド' },
      { it: 'la libreria', ja: '本屋' },

      // 店のなか
      { it: 'la cassa', ja: 'レジ' },
      { it: 'il commesso', ja: '店員（男性）' },
      { it: 'la commessa', ja: '店員（女性）' },
      { it: 'il carrello', ja: 'カート' },
      { it: 'il cestino', ja: '買い物かご' },
      { it: 'la busta', ja: '袋' },
      { it: 'la vetrina', ja: 'ショーウィンドー' },
      { it: 'il camerino', ja: '試着室' },
      { it: 'lo scaffale', ja: '棚' },
      { it: 'la fila', ja: '行列' },

      // 値段と支払い
      { it: "quant'è?", ja: 'おいくらですか' },
      { it: 'quanto viene?', ja: '合計いくらですか' },
      { it: 'il prezzo', ja: '値段' },
      { it: 'è caro', ja: '高い' },
      { it: 'è economico', ja: '安い' },
      { it: 'lo sconto', ja: '割引' },
      { it: 'i saldi', ja: 'セール', note: '夏と冬に時期が決まっている' },
      { it: "l'offerta", ja: '特売' },
      { it: 'gratis', ja: '無料' },
      { it: 'pagare', ja: '支払う' },
      { it: 'in contanti', ja: '現金で' },
      { it: 'con la carta', ja: 'カードで' },
      { it: 'il resto', ja: 'おつり' },
      { it: 'la ricevuta', ja: '領収書' },
      { it: 'il portafoglio', ja: '財布' },
      { it: 'i soldi', ja: 'お金' },
      { it: "l'euro", ja: 'ユーロ' },
      { it: 'il centesimo', ja: 'セント' },

      // やりとり
      { it: 'posso provare?', ja: '試着できますか' },
      { it: 'provare', ja: '試す' },
      { it: 'lo prendo', ja: 'これにします' },
      { it: 'sto solo guardando', ja: '見ているだけです' },
      { it: 'avete?', ja: 'ありますか' },
      { it: 'un altro colore', ja: '別の色' },
      { it: 'troppo grande', ja: '大きすぎる' },
      { it: 'troppo piccolo', ja: '小さすぎる' },
      { it: 'la taglia', ja: 'サイズ（服）' },
      { it: 'il numero', ja: 'サイズ（靴）' },
      { it: 'è aperto', ja: '開いている' },
      { it: 'è chiuso', ja: '閉まっている' },
      { it: "l'orario di apertura", ja: '営業時間' },
      { it: 'il regalo', ja: 'プレゼント' },
      { it: 'incartare', ja: '包装する' },

      // 色
      { it: 'il colore', ja: '色' },
      { it: 'rosso', ja: '赤' },
      { it: 'blu', ja: '青' },
      { it: 'verde', ja: '緑' },
      { it: 'giallo', ja: '黄' },
      { it: 'nero', ja: '黒' },
      { it: 'bianco', ja: '白' },
      { it: 'grigio', ja: '灰色' },
      { it: 'marrone', ja: '茶色' },

      // 服と持ちもの
      { it: 'la maglietta', ja: 'Tシャツ' },
      { it: 'la camicia', ja: 'シャツ' },
      { it: 'i pantaloni', ja: 'ズボン' },
      { it: 'la gonna', ja: 'スカート' },
      { it: 'il vestito', ja: 'ワンピース' },
      { it: 'la giacca', ja: 'ジャケット' },
      { it: 'il cappotto', ja: 'コート' },
      { it: 'le scarpe', ja: '靴' },
      { it: 'i calzini', ja: '靴下' },
      { it: 'la borsa', ja: 'バッグ' },
      { it: 'il cappello', ja: '帽子' },
      { it: 'gli occhiali', ja: 'めがね' },
    ],
  },

  {
    id: 'famiglia',
    ja: '家族',
    hint: 'la sorella / i nonni',
    entries: [
      // 近い家族
      { it: 'la famiglia', ja: '家族' },
      { it: 'i genitori', ja: '両親' },
      { it: 'il padre', ja: '父' },
      { it: 'la madre', ja: '母' },
      { it: 'il papà', ja: 'パパ' },
      { it: 'la mamma', ja: 'ママ' },
      { it: 'il figlio', ja: '息子' },
      { it: 'la figlia', ja: '娘' },
      { it: 'i figli', ja: '子どもたち', note: '男女が混ざれば男性形' },
      { it: 'il figlio unico', ja: '一人っ子' },
      { it: 'il fratello', ja: '兄弟' },
      { it: 'la sorella', ja: '姉妹' },
      { it: 'il fratello maggiore', ja: '兄' },
      { it: 'il fratello minore', ja: '弟' },
      { it: 'la sorella maggiore', ja: '姉' },
      { it: 'la sorella minore', ja: '妹' },

      // 親戚
      { it: 'il nonno', ja: '祖父' },
      { it: 'la nonna', ja: '祖母' },
      { it: 'i nonni', ja: '祖父母' },
      { it: 'lo zio', ja: 'おじ' },
      { it: 'la zia', ja: 'おば' },
      { it: 'il cugino', ja: 'いとこ（男）' },
      { it: 'la cugina', ja: 'いとこ（女）' },
      { it: 'il nipote', ja: '孫、甥', note: '孫と甥の両方を指す' },
      { it: 'la nipote', ja: '孫娘、姪' },
      { it: 'il parente', ja: '親戚' },

      // 結婚まわり
      { it: 'il marito', ja: '夫' },
      { it: 'la moglie', ja: '妻' },
      { it: 'il fidanzato', ja: '恋人（男）' },
      { it: 'la fidanzata', ja: '恋人（女）' },
      { it: 'sposarsi', ja: '結婚する' },
      { it: 'il matrimonio', ja: '結婚式' },
      { it: 'sposato', ja: '既婚の' },
      { it: 'single', ja: '独身の' },
      { it: 'divorziato', ja: '離婚した' },
      { it: 'il suocero', ja: '義父' },
      { it: 'la suocera', ja: '義母' },
      { it: 'i suoceri', ja: '義理の両親' },
      { it: 'il genero', ja: '娘の夫' },
      { it: 'la nuora', ja: '息子の妻' },
      { it: 'il cognato', ja: '義理の兄弟' },
      { it: 'la cognata', ja: '義理の姉妹' },

      // 人を指す言葉
      { it: 'il bambino', ja: '男の子' },
      { it: 'la bambina', ja: '女の子' },
      { it: 'il ragazzo', ja: '若者（男）' },
      { it: 'la ragazza', ja: '若者（女）' },
      { it: "l'uomo", ja: '男の人' },
      { it: 'la donna', ja: '女の人' },
      { it: 'il signore', ja: '男性（敬称）' },
      { it: 'la signora', ja: '女性（敬称）' },
      { it: "l'amico", ja: '友だち（男）' },
      { it: "l'amica", ja: '友だち（女）' },
      { it: 'il vicino', ja: '隣人' },
      { it: 'il collega', ja: '同僚' },

      // たずねる
      { it: 'quanti anni hai?', ja: '何歳ですか' },
      { it: "ho trent'anni", ja: '30歳です' },
      { it: 'sei sposato?', ja: '結婚してますか' },
      { it: 'hai figli?', ja: '子どもはいますか' },
      { it: 'hai fratelli?', ja: '兄弟はいますか' },
      { it: 'abito con', ja: '〜と住んでいます' },
      { it: 'il nome', ja: '名前' },
      { it: 'il cognome', ja: '名字' },
      { it: 'il compleanno', ja: '誕生日' },
      { it: 'la casa', ja: '家' },

      // 人を説明する
      { it: 'maggiore', ja: '年上の' },
      { it: 'minore', ja: '年下の' },
      { it: 'giovane', ja: '若い' },
      { it: 'anziano', ja: '年配の' },
      { it: 'simpatico', ja: '感じがいい' },
      { it: 'gentile', ja: '親切な' },
      { it: 'alto', ja: '背が高い' },
      { it: 'basso', ja: '背が低い' },
      { it: 'assomigliare', ja: '似ている' },
      { it: 'il gatto', ja: '猫' },
      { it: 'il cane', ja: '犬' },
    ],
  },

  {
    id: 'calcio',
    ja: 'カルチョ',
    hint: 'il rigore / Forza!',
    entries: [
      // 基本
      { it: 'il calcio', ja: 'サッカー' },
      { it: 'la partita', ja: '試合' },
      { it: 'la squadra', ja: 'チーム' },
      { it: 'il tifoso', ja: 'サポーター' },
      { it: 'tifare', ja: '応援する', note: 'tifare per + チーム名' },
      { it: 'il gol', ja: 'ゴール' },
      { it: 'segnare', ja: '得点する' },
      { it: 'lo stadio', ja: 'スタジアム' },
      { it: 'il derby', ja: 'ダービー' },

      // 人
      { it: 'il giocatore', ja: '選手' },
      { it: 'il portiere', ja: 'ゴールキーパー' },
      { it: 'il difensore', ja: 'ディフェンダー' },
      { it: 'il centrocampista', ja: 'ミッドフィルダー' },
      { it: "l'attaccante", ja: 'フォワード' },
      { it: 'il capitano', ja: 'キャプテン' },
      { it: 'la riserva', ja: '控え選手' },
      { it: 'il bomber', ja: '点取り屋', note: '決定力のある FW を指す口語' },
      { it: "l'allenatore", ja: '監督' },
      { it: "l'arbitro", ja: '主審' },
      { it: 'il guardalinee', ja: '線審', note: '正式には assistente arbitrale' },
      { it: 'la Nazionale', ja: '代表チーム', note: 'イタリア代表の愛称は gli Azzurri' },
      { it: 'la panchina', ja: 'ベンチ' },

      // プレー
      { it: 'il passaggio', ja: 'パス' },
      { it: 'il tiro', ja: 'シュート' },
      { it: 'il cross', ja: 'クロス' },
      { it: 'il colpo di testa', ja: 'ヘディング' },
      { it: 'la rovesciata', ja: 'オーバーヘッドキック' },
      { it: 'il dribbling', ja: 'ドリブル' },
      { it: 'la parata', ja: 'セーブ', note: 'portiere がシュートを止めること' },
      { it: 'il contropiede', ja: 'カウンター' },
      { it: 'il possesso palla', ja: 'ボール支配率' },
      { it: 'il palo', ja: 'ゴールポスト' },
      { it: 'la traversa', ja: 'クロスバー' },
      { it: 'la rete', ja: 'ゴールネット', note: '実況では得点そのものも rete と言う' },
      { it: "l'autogol", ja: 'オウンゴール' },

      // 判定
      { it: 'il fallo', ja: 'ファウル' },
      { it: 'il rigore', ja: 'PK' },
      { it: "il calcio d'angolo", ja: 'コーナーキック' },
      { it: 'la punizione', ja: 'フリーキック' },
      { it: 'il fuorigioco', ja: 'オフサイド' },
      { it: 'il cartellino giallo', ja: 'イエローカード' },
      { it: 'il cartellino rosso', ja: 'レッドカード' },
      { it: "l'ammonizione", ja: '警告', note: 'カードそのものは cartellino' },
      { it: "l'espulsione", ja: '退場' },
      { it: 'il VAR', ja: 'ビデオ判定' },
      { it: 'il fischio', ja: 'ホイッスル' },

      // 試合の流れ
      { it: "il calcio d'inizio", ja: 'キックオフ' },
      { it: 'il primo tempo', ja: '前半' },
      { it: 'il secondo tempo', ja: '後半' },
      { it: 'il recupero', ja: 'アディショナルタイム' },
      { it: 'il tempo supplementare', ja: '延長戦' },
      { it: 'i rigori', ja: 'PK戦', note: '延長でも決まらないときの決着' },
      { it: "l'infortunio", ja: 'けが' },
      { it: 'la sostituzione', ja: '選手交代' },

      // 勝ち負けと順位
      { it: 'il pareggio', ja: '引き分け' },
      { it: 'la vittoria', ja: '勝利' },
      { it: 'la sconfitta', ja: '敗北' },
      { it: 'il campionato', ja: 'リーグ戦' },
      { it: 'la coppa', ja: 'カップ戦' },
      { it: 'la Serie A', ja: 'セリエA' },
      { it: 'lo scudetto', ja: 'リーグ優勝', note: '優勝チームが翌季つける盾の印' },
      { it: 'la retrocessione', ja: '降格' },
      { it: 'la promozione', ja: '昇格' },
      { it: 'il girone', ja: 'グループリーグ' },
      { it: 'la classifica', ja: '順位表' },
      { it: 'la trasferta', ja: 'アウェー' },
      { it: 'in casa', ja: 'ホームで' },
      { it: 'il punteggio', ja: 'スコア' },
      { it: 'i punti', ja: '勝ち点' },

      // スタジアムで
      { it: 'la curva', ja: 'ゴール裏', note: '熱心なサポーターが陣取る席' },
      { it: 'il coro', ja: 'チャント' },
      { it: 'lo striscione', ja: '横断幕' },
      { it: 'forza!', ja: 'がんばれ！' },
      { it: 'dai!', ja: 'いけ！、ほら！' },
      { it: 'che gol!', ja: 'なんてゴールだ！' },
    ],
  },
];

export const TOPIC_IDS = TOPICS.map((t) => t.id);

export const topicById = (id) => TOPICS.find((t) => t.id === id) ?? null;

/** エントリ数（設定画面の表示用） */
export const topicSize = (id) => topicById(id)?.entries.length ?? 0;
