/**
 * よく使う単語・表現。
 *
 * 数字と違って生成できないので、ここに直接並べる。話題ごとに分けてあるのは
 * 選択肢を作るときに「同じ話題の中から」誤答を採るため。ciao の誤答が
 * portiere だと、意味を知らなくても消去法で当たってしまう。
 *
 * イタリア語側には冠詞をつけてある。名詞の性はまとめて覚えるほうが早いし、
 * 実際に口に出すときも冠詞ごと出てくるほうが使える。
 *
 * note は「日本語訳だけでは落ちない情報」があるときだけ書く。
 * 使い分け（scusa / scusi）、習慣（cappuccino は朝だけ）、決まった返し方など。
 */

export const TOPICS = [
  {
    id: 'saluti',
    ja: 'あいさつ',
    hint: 'ciao / grazie',
    entries: [
      { it: 'ciao', ja: 'やあ、じゃあね', note: '親しい相手に。会うときも別れるときも使う' },
      { it: 'salve', ja: 'どうも', note: 'ciao より丁寧で buongiorno より軽い' },
      { it: 'buongiorno', ja: 'おはよう、こんにちは' },
      { it: 'buonasera', ja: 'こんばんは', note: '夕方から。会ったときのあいさつ' },
      { it: 'buonanotte', ja: 'おやすみ', note: '別れ際か寝る前だけ。出会いには使わない' },
      { it: 'arrivederci', ja: 'さようなら' },
      { it: 'a presto', ja: 'またすぐに' },
      { it: 'a domani', ja: 'また明日' },
      { it: 'a dopo', ja: 'またあとで' },
      { it: 'ci vediamo', ja: 'また会おうね' },
      { it: 'come stai?', ja: '元気？', note: '親しい相手に。丁寧には come sta?' },
      { it: 'come sta?', ja: 'お元気ですか', note: '目上・初対面に' },
      { it: 'sto bene', ja: '元気です' },
      { it: "non c'è male", ja: 'まあまあです' },
      { it: 'e tu?', ja: '君は？' },
      { it: 'piacere', ja: 'はじめまして' },
      // per piacere も同義。別項目にすると「お願いします」に正解が2つできて
      // しまうので、注記でまとめて覚えさせる。
      { it: 'per favore', ja: 'お願いします', note: '同じ意味で per piacere とも言う' },
      { it: 'grazie', ja: 'ありがとう' },
      { it: 'grazie mille', ja: 'どうもありがとう' },
      { it: 'prego', ja: 'どういたしまして', note: '「どうぞ」の意味でも使う' },
      { it: 'scusa', ja: 'ごめん', note: '親しい相手に。丁寧には scusi' },
      { it: 'scusi', ja: 'すみません', note: '知らない人に呼びかけるときも' },
      { it: 'mi dispiace', ja: '残念です', note: '気の毒に思うときの言い方。軽い謝罪にも' },
      { it: 'permesso', ja: '失礼します', note: '人の前を通るとき、部屋に入るとき' },
      { it: 'buon appetito', ja: 'めしあがれ', note: '食事を始める人にかける言葉' },
      { it: 'auguri', ja: 'おめでとう' },
      { it: 'in bocca al lupo', ja: 'がんばって', note: '返しは crepi（il lupo）' },
      { it: 'buona giornata', ja: 'よい一日を' },
      { it: 'buon fine settimana', ja: 'よい週末を' },
    ],
  },
  {
    id: 'bar',
    ja: 'バール・食事',
    hint: 'caffè / il conto',
    entries: [
      { it: 'un caffè', ja: 'エスプレッソ', note: 'イタリアで caffè といえばエスプレッソ' },
      { it: 'un cappuccino', ja: 'カプチーノ', note: '朝に飲むもの。食後には頼まない' },
      { it: 'un cornetto', ja: 'クロワッサン' },
      { it: 'al banco', ja: 'カウンターで', note: '座って飲むより安い' },
      { it: 'lo scontrino', ja: 'レシート', note: 'バールでは先に払ってレシートを見せる' },
      { it: 'da portare via', ja: '持ち帰りで' },
      { it: 'il conto', ja: 'お会計' },
      { it: 'il coperto', ja: '席料', note: '一人あたりにかかる。伝票に載る' },
      { it: 'la mancia', ja: 'チップ' },
      { it: 'vorrei', ja: '〜が欲しいのですが', note: 'voglio より丁寧。注文はこれで' },
      { it: 'un tavolo per due', ja: '2人用のテーブル' },
      { it: 'il menù', ja: 'メニュー' },
      { it: "l'antipasto", ja: '前菜' },
      { it: 'il primo', ja: '第一の皿', note: 'パスタ・リゾットなど' },
      { it: 'il secondo', ja: '第二の皿', note: '肉か魚。つけ合わせは別に頼む' },
      { it: 'il contorno', ja: 'つけ合わせ' },
      { it: 'il dolce', ja: 'デザート' },
      { it: 'acqua naturale', ja: '炭酸なしの水' },
      { it: 'acqua frizzante', ja: '炭酸水' },
      { it: 'il vino rosso', ja: '赤ワイン' },
      { it: 'il vino bianco', ja: '白ワイン' },
      { it: 'la birra', ja: 'ビール' },
      { it: 'il pane', ja: 'パン' },
      { it: 'il gelato', ja: 'ジェラート' },
      { it: 'il cameriere', ja: 'ウェイター' },
      { it: 'ho fame', ja: 'お腹がすいた' },
      { it: 'ho sete', ja: 'のどが渇いた' },
      { it: 'buonissimo', ja: 'とてもおいしい' },
      { it: 'basta così', ja: 'これで十分です' },
      { it: 'cin cin', ja: '乾杯' },
    ],
  },
  {
    id: 'treno',
    ja: '電車・移動',
    hint: 'il binario / in ritardo',
    entries: [
      { it: 'il treno', ja: '電車' },
      { it: 'la stazione', ja: '駅' },
      { it: 'il binario', ja: '〜番線', note: 'binario 5 のように番号をつけて言う' },
      { it: 'il biglietto', ja: '切符' },
      { it: 'la biglietteria', ja: '切符売り場' },
      { it: 'convalidare', ja: '（切符を）刻印する', note: '乗る前に刻印しないと罰金' },
      { it: 'andata e ritorno', ja: '往復' },
      { it: 'solo andata', ja: '片道' },
      { it: 'la coincidenza', ja: '乗り換え' },
      { it: 'in ritardo', ja: '遅れて' },
      { it: 'in orario', ja: '定刻で' },
      { it: 'lo sciopero', ja: 'ストライキ', note: '交通機関では珍しくない' },
      { it: 'la fermata', ja: '停留所' },
      { it: 'salire', ja: '乗る' },
      { it: 'scendere', ja: '降りる' },
      { it: 'il posto', ja: '席' },
      { it: 'prenotare', ja: '予約する' },
      { it: 'la carrozza', ja: '車両' },
      { it: 'il capolinea', ja: '終点' },
      { it: 'la metropolitana', ja: '地下鉄' },
      { it: "l'autobus", ja: 'バス' },
      { it: 'il pullman', ja: '長距離バス' },
      { it: 'il regionale', ja: '各駅停車', note: '速いのは Frecciarossa など' },
      { it: 'la partenza', ja: '出発' },
      { it: "l'arrivo", ja: '到着' },
      { it: 'a che ora parte?', ja: '何時発ですか' },
      { it: 'a che ora arriva?', ja: '何時着ですか' },
      { it: 'quanto costa?', ja: 'いくらですか' },
      { it: "dov'è?", ja: 'どこですか' },
      { it: 'il ritardo', ja: '遅延' },
    ],
  },
  {
    id: 'calcio',
    ja: 'カルチョ',
    hint: 'il rigore / Forza!',
    entries: [
      { it: 'il calcio', ja: 'サッカー' },
      { it: 'la partita', ja: '試合' },
      { it: 'la squadra', ja: 'チーム' },
      { it: 'il tifoso', ja: 'サポーター' },
      { it: 'tifare', ja: '応援する', note: 'tifare per + チーム名' },
      { it: 'il gol', ja: 'ゴール' },
      { it: 'segnare', ja: '得点する' },
      { it: 'il portiere', ja: 'ゴールキーパー' },
      { it: 'il difensore', ja: 'ディフェンダー' },
      { it: 'il centrocampista', ja: 'ミッドフィルダー' },
      { it: "l'attaccante", ja: 'フォワード' },
      { it: "l'arbitro", ja: '主審' },
      { it: 'il fallo', ja: 'ファウル' },
      { it: 'il rigore', ja: 'PK' },
      { it: "il calcio d'angolo", ja: 'コーナーキック' },
      { it: 'la punizione', ja: 'フリーキック' },
      { it: 'il fuorigioco', ja: 'オフサイド' },
      { it: 'il cartellino giallo', ja: 'イエローカード' },
      { it: 'il cartellino rosso', ja: 'レッドカード' },
      { it: 'il primo tempo', ja: '前半' },
      { it: 'il secondo tempo', ja: '後半' },
      { it: 'il recupero', ja: 'アディショナルタイム' },
      { it: 'il pareggio', ja: '引き分け' },
      { it: 'la vittoria', ja: '勝利' },
      { it: 'la sconfitta', ja: '敗北' },
      { it: 'il campionato', ja: 'リーグ戦' },
      { it: 'la coppa', ja: 'カップ戦' },
      { it: "l'allenatore", ja: '監督' },
      { it: 'la panchina', ja: 'ベンチ' },
      { it: 'lo stadio', ja: 'スタジアム' },
      { it: 'la classifica', ja: '順位表' },
      { it: 'il derby', ja: 'ダービー' },
      { it: 'forza!', ja: 'がんばれ！' },
      { it: 'dai!', ja: 'いけ！、ほら！' },

      // 人
      { it: 'il giocatore', ja: '選手' },
      { it: 'il capitano', ja: 'キャプテン' },
      { it: 'la riserva', ja: '控え選手' },
      { it: 'il bomber', ja: '点取り屋', note: '決定力のある FW を指す口語' },
      { it: 'il guardalinee', ja: '線審', note: '正式には assistente arbitrale' },
      {
        it: 'la Nazionale',
        ja: '代表チーム',
        note: 'イタリア代表の愛称は gli Azzurri',
      },

      // プレー
      { it: 'il passaggio', ja: 'パス' },
      { it: 'il tiro', ja: 'シュート' },
      { it: 'il cross', ja: 'クロス' },
      { it: 'il colpo di testa', ja: 'ヘディング' },
      { it: 'la rovesciata', ja: 'オーバーヘッドキック' },
      { it: 'il dribbling', ja: 'ドリブル' },
      { it: 'la parata', ja: 'セーブ', note: 'portiere がシュートを止めること' },
      { it: 'il contropiede', ja: 'カウンター' },
      { it: 'il possesso palla', ja: 'ボール支配率' },
      { it: 'il palo', ja: 'ゴールポスト' },
      { it: 'la traversa', ja: 'クロスバー' },
      { it: 'la rete', ja: 'ゴールネット', note: '実況では得点そのものも rete と言う' },
      { it: "l'autogol", ja: 'オウンゴール' },

      // 試合の流れ
      { it: "il calcio d'inizio", ja: 'キックオフ' },
      { it: 'il tempo supplementare', ja: '延長戦' },
      { it: 'i rigori', ja: 'PK戦', note: '延長でも決まらないときの決着' },
      { it: "l'ammonizione", ja: '警告', note: 'カードそのものは cartellino' },
      { it: "l'espulsione", ja: '退場' },
      { it: "l'infortunio", ja: 'けが' },
      { it: 'la sostituzione', ja: '選手交代' },
      { it: 'il VAR', ja: 'ビデオ判定' },
      { it: 'il fischio', ja: 'ホイッスル' },

      // リーグと順位
      { it: 'la Serie A', ja: 'セリエA' },
      { it: 'lo scudetto', ja: 'リーグ優勝', note: '優勝チームが翌季つける盾の印' },
      { it: 'la retrocessione', ja: '降格' },
      { it: 'la promozione', ja: '昇格' },
      { it: 'il girone', ja: 'グループリーグ' },
      { it: 'la trasferta', ja: 'アウェー' },
      { it: 'in casa', ja: 'ホームで' },
      { it: 'il punteggio', ja: 'スコア' },
      { it: 'i punti', ja: '勝ち点' },

      // スタジアムで
      { it: 'la curva', ja: 'ゴール裏', note: '熱心なサポーターが陣取る席' },
      { it: 'il coro', ja: 'チャント' },
      { it: 'lo striscione', ja: '横断幕' },
      { it: 'che gol!', ja: 'なんてゴールだ！' },
    ],
  },
];

export const TOPIC_IDS = TOPICS.map((t) => t.id);

export const topicById = (id) => TOPICS.find((t) => t.id === id) ?? null;

/** 全エントリ数（設定画面の表示用） */
export const topicSize = (id) => topicById(id)?.entries.length ?? 0;
