/**
 * よく使う単語・表現。
 *
 * 数字と違って生成できないので、ここに直接並べる。話題ごとに分けてあるのは
 * 選択肢を作るときに「同じ話題の中から」誤答を採るため。ciao の誤答が
 * portiere だと、意味を知らなくても消去法で当たってしまう。
 *
 * イタリア語側には冠詞をつけてある。名詞の性はまとめて覚えるほうが早いし、
 * 実際に口に出すときも冠詞ごと出てくるほうが使える。
 *
 * note は「日本語訳だけでは落ちない情報」があるときだけ書く。
 * 使い分け（scusa / scusi）、習慣（cappuccino は朝だけ）、決まった返し方など。
 *
 * 同じ話題の中では it も ja も重複させないこと。訳が重なると
 * 「正解が2つある問題」ができてしまう（テストで検査している）。
 */

export const TOPICS = [
  {
    id: 'saluti',
    ja: 'あいさつ',
    hint: 'ciao / grazie',
    entries: [
      // 出会いと別れ
      { it: 'ciao', ja: 'やあ、じゃあね', note: '親しい相手に。会うときも別れるときも使う' },
      { it: 'salve', ja: 'どうも', note: 'ciao より丁寧で buongiorno より軽い' },
      { it: 'buongiorno', ja: 'おはよう、こんにちは' },
      { it: 'buonasera', ja: 'こんばんは', note: '夕方から。会ったときのあいさつ' },
      { it: 'buonanotte', ja: 'おやすみ', note: '別れ際か寝る前だけ。出会いには使わない' },
      { it: 'arrivederci', ja: 'さようなら' },
      { it: 'arrivederla', ja: 'さようなら（丁寧）', note: '目上の人ひとりに' },
      { it: 'a presto', ja: 'またすぐに' },
      { it: 'a domani', ja: 'また明日' },
      { it: 'a dopo', ja: 'またあとで' },
      { it: 'ci vediamo', ja: 'また会おうね' },
      { it: 'ci sentiamo', ja: 'また連絡するね', note: '電話やメッセージで' },
      { it: 'benvenuto', ja: 'ようこそ' },

      // 調子をたずねる
      { it: 'come stai?', ja: '元気？', note: '親しい相手に。丁寧には come sta?' },
      { it: 'come sta?', ja: 'お元気ですか', note: '目上・初対面に' },
      { it: 'come va?', ja: '調子どう？' },
      { it: 'tutto bene?', ja: '大丈夫？' },
      { it: 'sto bene', ja: '元気です' },
      { it: 'benissimo', ja: 'とても元気' },
      { it: "non c'è male", ja: 'まあまあです' },
      { it: 'così così', ja: 'ぼちぼち' },
      { it: 'e tu?', ja: '君は？' },
      { it: 'e Lei?', ja: 'あなたは？', note: '丁寧に聞き返すとき' },

      // 自己紹介
      { it: 'piacere', ja: 'はじめまして' },
      { it: 'molto lieto', ja: 'お会いできて光栄です' },
      { it: 'come ti chiami?', ja: '名前は？' },
      { it: 'mi chiamo', ja: '私の名前は' },
      { it: 'di dove sei?', ja: 'どこの出身？' },
      { it: 'sono giapponese', ja: '日本人です' },

      // 礼と詫び
      { it: 'per favore', ja: 'お願いします', note: '同じ意味で per piacere とも言う' },
      { it: 'grazie', ja: 'ありがとう' },
      { it: 'grazie mille', ja: 'どうもありがとう' },
      { it: 'grazie di tutto', ja: 'いろいろありがとう' },
      { it: 'prego', ja: 'どういたしまして', note: '「どうぞ」の意味でも使う' },
      { it: 'di niente', ja: 'とんでもない' },
      { it: 'figurati', ja: '気にしないで' },
      { it: 'scusa', ja: 'ごめん', note: '親しい相手に。丁寧には scusi' },
      { it: 'scusi', ja: 'すみません', note: '知らない人に呼びかけるときも' },
      { it: 'mi dispiace', ja: '残念です', note: '気の毒に思うときの言い方。軽い謝罪にも' },
      { it: 'permesso', ja: '失礼します', note: '人の前を通るとき、部屋に入るとき' },
      { it: 'non ti preoccupare', ja: '心配しないで' },

      // 聞き返す・分からない
      { it: 'non capisco', ja: '分かりません' },
      { it: 'non lo so', ja: '知りません' },
      { it: 'come?', ja: 'え？', note: '聞き取れなかったときの聞き返し' },
      { it: 'puoi ripetere?', ja: 'もう一度言って' },
      { it: 'più lentamente', ja: 'もっとゆっくり' },
      { it: 'come si dice?', ja: '何と言いますか' },
      { it: 'che cosa significa?', ja: 'どういう意味ですか' },
      { it: 'parli inglese?', ja: '英語を話せますか' },

      // 返事
      { it: 'va bene', ja: 'いいですよ' },
      { it: "d'accordo", ja: '賛成です' },
      { it: 'certo', ja: 'もちろん' },
      { it: 'volentieri', ja: '喜んで' },
      { it: 'purtroppo', ja: '残念ながら' },
      { it: 'forse', ja: 'たぶん' },
      { it: 'meno male', ja: 'よかった' },
      { it: 'che peccato!', ja: '残念！' },
      { it: 'pronto?', ja: 'もしもし', note: '電話に出るとき' },
      { it: 'si accomodi', ja: 'どうぞお掛けください' },

      // 決まり文句
      { it: 'buon appetito', ja: 'めしあがれ', note: '食事を始める人にかける言葉' },
      { it: 'auguri', ja: 'おめでとう' },
      { it: 'congratulazioni', ja: '合格おめでとう', note: '成果をあげた人に' },
      { it: 'in bocca al lupo', ja: 'がんばって', note: '返しは crepi（il lupo）' },
      { it: 'buona giornata', ja: 'よい一日を' },
      { it: 'buona serata', ja: 'よい夜を' },
      { it: 'buon fine settimana', ja: 'よい週末を' },
      { it: 'buon viaggio', ja: 'よい旅を' },
      { it: 'buon lavoro', ja: '仕事がんばって' },
      { it: 'buone vacanze', ja: 'よい休暇を' },
      { it: 'buon compleanno', ja: '誕生日おめでとう' },
      { it: 'buon Natale', ja: 'メリークリスマス' },
      { it: 'buon anno', ja: 'あけましておめでとう' },
      { it: 'salute!', ja: 'お大事に', note: 'くしゃみをした人にかける' },
    ],
  },

  {
    id: 'bar',
    ja: 'バール・食事',
    hint: 'caffè / il conto',
    entries: [
      // バールで
      { it: 'un caffè', ja: 'エスプレッソ', note: 'イタリアで caffè といえばエスプレッソ' },
      { it: 'un cappuccino', ja: 'カプチーノ', note: '朝に飲むもの。食後には頼まない' },
      { it: 'un caffè macchiato', ja: 'マキアート', note: 'エスプレッソに少しミルク' },
      { it: 'un latte macchiato', ja: 'ラテマキアート', note: 'ミルクに少しコーヒー' },
      { it: 'un caffè corretto', ja: 'お酒入りコーヒー' },
      { it: 'un cornetto', ja: 'クロワッサン' },
      { it: 'una brioche', ja: '菓子パン' },
      { it: 'al banco', ja: 'カウンターで', note: '座って飲むより安い' },
      { it: 'al tavolo', ja: 'テーブルで' },
      { it: 'lo scontrino', ja: 'レシート', note: 'バールでは先に払ってレシートを見せる' },
      { it: 'da portare via', ja: '持ち帰りで' },

      // 注文と会計
      { it: 'vorrei', ja: '〜が欲しいのですが', note: 'voglio より丁寧。注文はこれで' },
      { it: 'un tavolo per due', ja: '2人用のテーブル' },
      { it: 'il menù', ja: 'メニュー' },
      { it: 'la carta dei vini', ja: 'ワインリスト' },
      { it: 'il conto', ja: 'お会計' },
      { it: 'il coperto', ja: '席料', note: '一人あたりにかかる。伝票に載る' },
      { it: 'la mancia', ja: 'チップ' },
      { it: 'il cameriere', ja: 'ウェイター' },
      { it: 'sono vegetariano', ja: 'ベジタリアンです' },
      { it: 'senza glutine', ja: 'グルテンなし' },
      { it: 'è piccante?', ja: '辛いですか' },
      { it: 'basta così', ja: 'これで十分です' },

      // コースの構成
      { it: "l'antipasto", ja: '前菜' },
      { it: 'il primo', ja: '第一の皿', note: 'パスタ・リゾットなど' },
      { it: 'il secondo', ja: '第二の皿', note: '肉か魚。つけ合わせは別に頼む' },
      { it: 'il contorno', ja: 'つけ合わせ' },
      { it: 'il dolce', ja: 'デザート' },
      { it: 'la colazione', ja: '朝食' },
      { it: 'il pranzo', ja: '昼食' },
      { it: 'la cena', ja: '夕食' },

      // 飲みもの
      { it: 'acqua naturale', ja: '炭酸なしの水' },
      { it: 'acqua frizzante', ja: '炭酸水' },
      { it: 'il vino rosso', ja: '赤ワイン' },
      { it: 'il vino bianco', ja: '白ワイン' },
      { it: 'il vino della casa', ja: 'ハウスワイン' },
      { it: 'lo spumante', ja: 'スパークリングワイン' },
      { it: 'la birra', ja: 'ビール' },
      { it: 'il latte', ja: '牛乳' },
      { it: 'cin cin', ja: '乾杯' },

      // 食べもの
      { it: 'il pane', ja: 'パン' },
      { it: 'la pasta', ja: 'パスタ' },
      { it: 'gli spaghetti', ja: 'スパゲッティ' },
      { it: 'la pizza', ja: 'ピザ' },
      { it: 'il risotto', ja: 'リゾット' },
      { it: 'la zuppa', ja: 'スープ' },
      { it: 'il riso', ja: '米' },
      { it: 'la carne', ja: '肉' },
      { it: 'il pesce', ja: '魚' },
      { it: 'il pollo', ja: '鶏肉' },
      { it: 'il manzo', ja: '牛肉' },
      { it: 'il maiale', ja: '豚肉' },
      { it: 'il prosciutto', ja: '生ハム' },
      { it: 'il formaggio', ja: 'チーズ' },
      { it: 'la verdura', ja: '野菜' },
      { it: "l'insalata", ja: 'サラダ' },
      { it: 'la frutta', ja: '果物' },
      { it: "l'uovo", ja: '卵' },
      { it: 'il gelato', ja: 'ジェラート' },

      // 調味料と食器
      { it: 'il sale', ja: '塩' },
      { it: 'il pepe', ja: 'こしょう' },
      { it: "l'olio", ja: 'オリーブオイル' },
      { it: "l'aceto", ja: '酢' },
      { it: 'il burro', ja: 'バター' },
      { it: 'lo zucchero', ja: '砂糖' },
      { it: 'il cucchiaio', ja: 'スプーン' },
      { it: 'la forchetta', ja: 'フォーク' },
      { it: 'il coltello', ja: 'ナイフ' },
      { it: 'il bicchiere', ja: 'コップ' },
      { it: 'la tazza', ja: 'カップ' },
      { it: 'il tovagliolo', ja: 'ナプキン' },

      // 感想
      { it: 'ho fame', ja: 'お腹がすいた' },
      { it: 'ho sete', ja: 'のどが渇いた' },
      { it: 'buonissimo', ja: 'とてもおいしい' },
    ],
  },

  {
    id: 'treno',
    ja: '電車・移動',
    hint: 'il binario / in ritardo',
    entries: [
      // 駅と切符
      { it: 'il treno', ja: '電車' },
      { it: 'la stazione', ja: '駅' },
      { it: 'il binario', ja: '〜番線', note: 'binario cinque のように番号をつけて言う' },
      { it: 'il biglietto', ja: '切符' },
      { it: 'la biglietteria', ja: '切符売り場' },
      { it: 'convalidare', ja: '（切符を）刻印する', note: '乗る前に刻印しないと罰金' },
      { it: 'andata e ritorno', ja: '往復' },
      { it: 'solo andata', ja: '片道' },
      { it: 'prenotare', ja: '予約する' },
      { it: 'il tabellone', ja: '発車案内板' },
      { it: "la sala d'attesa", ja: '待合室' },
      { it: 'il deposito bagagli', ja: '荷物預かり所' },

      // 乗り降り
      { it: 'la coincidenza', ja: '乗り換え' },
      { it: 'salire', ja: '乗る' },
      { it: 'scendere', ja: '降りる' },
      { it: 'il posto', ja: '席' },
      { it: 'la carrozza', ja: '車両' },
      { it: 'la fermata', ja: '停留所' },
      { it: 'il capolinea', ja: '終点' },
      { it: 'il controllore', ja: '車掌' },

      // 時間と乱れ
      { it: 'in ritardo', ja: '遅れて' },
      { it: 'in orario', ja: '定刻で' },
      { it: 'il ritardo', ja: '遅延' },
      { it: 'lo sciopero', ja: 'ストライキ', note: '交通機関では珍しくない' },
      { it: 'la partenza', ja: '出発' },
      { it: "l'arrivo", ja: '到着' },
      { it: 'a che ora parte?', ja: '何時発ですか' },
      { it: 'a che ora arriva?', ja: '何時着ですか' },
      { it: 'quanto ci vuole?', ja: 'どのくらいかかりますか' },

      // 乗りもの
      { it: 'il regionale', ja: '各駅停車', note: '速いのは Frecciarossa など' },
      { it: 'la metropolitana', ja: '地下鉄' },
      { it: "l'autobus", ja: 'バス' },
      { it: 'il pullman', ja: '長距離バス' },
      { it: 'il taxi', ja: 'タクシー' },
      { it: "l'aereo", ja: '飛行機' },
      { it: "l'aeroporto", ja: '空港' },
      { it: 'il traghetto', ja: 'フェリー' },
      { it: 'la nave', ja: '船' },
      { it: 'la bicicletta', ja: '自転車' },
      { it: 'la macchina', ja: '車' },
      { it: 'a piedi', ja: '徒歩で' },

      // 荷物と持ちもの
      { it: 'il bagaglio', ja: '荷物' },
      { it: 'la valigia', ja: 'スーツケース' },
      { it: 'lo zaino', ja: 'リュック' },
      { it: 'il passaporto', ja: 'パスポート' },
      { it: 'la patente', ja: '運転免許証' },
      { it: 'la mappa', ja: '地図' },

      // 建物のなか
      { it: "l'uscita", ja: '出口' },
      { it: "l'entrata", ja: '入口' },
      { it: 'il sottopassaggio', ja: '地下通路' },
      { it: 'la scala mobile', ja: 'エスカレーター' },
      { it: "l'ascensore", ja: 'エレベーター' },
      { it: 'il parcheggio', ja: '駐車場' },
      { it: 'la benzina', ja: 'ガソリン' },

      // 道をたずねる
      { it: "dov'è?", ja: 'どこですか' },
      { it: 'quanto costa?', ja: 'いくらですか' },
      { it: 'come si arriva?', ja: 'どうやって行きますか' },
      { it: 'mi sono perso', ja: '道に迷いました' },
      { it: 'a destra', ja: '右に' },
      { it: 'a sinistra', ja: '左に' },
      { it: 'sempre dritto', ja: 'まっすぐ' },
      { it: 'vicino', ja: '近い' },
      { it: 'lontano', ja: '遠い' },
      { it: 'qui', ja: 'ここ' },
      { it: 'là', ja: 'あそこ' },
      { it: "l'angolo", ja: '角' },
      { it: 'il semaforo', ja: '信号' },
      { it: 'la piazza', ja: '広場' },
      { it: 'la via', ja: '通り' },
      { it: 'il ponte', ja: '橋' },
      { it: 'il centro', ja: '中心街' },
      { it: 'la periferia', ja: '郊外' },
    ],
  },

  {
    id: 'negozio',
    ja: '買い物',
    hint: "quant'è? / lo sconto",
    entries: [
      // 店
      { it: 'il negozio', ja: '店' },
      { it: 'il supermercato', ja: 'スーパー' },
      { it: 'il mercato', ja: '市場' },
      { it: 'il centro commerciale', ja: 'ショッピングセンター' },
      { it: 'la panetteria', ja: 'パン屋' },
      { it: 'la pasticceria', ja: 'ケーキ屋' },
      { it: 'la macelleria', ja: '肉屋' },
      { it: 'la pescheria', ja: '魚屋' },
      { it: 'la farmacia', ja: '薬局' },
      { it: 'il tabaccaio', ja: 'タバコ屋', note: '切手やバスの切符もここで買える' },
      { it: "l'edicola", ja: '新聞スタンド' },
      { it: 'la libreria', ja: '本屋' },

      // 店のなか
      { it: 'la cassa', ja: 'レジ' },
      { it: 'il commesso', ja: '店員（男性）' },
      { it: 'la commessa', ja: '店員（女性）' },
      { it: 'il carrello', ja: 'カート' },
      { it: 'il cestino', ja: '買い物かご' },
      { it: 'la busta', ja: '袋' },
      { it: 'la vetrina', ja: 'ショーウィンドー' },
      { it: 'il camerino', ja: '試着室' },
      { it: 'lo scaffale', ja: '棚' },
      { it: 'la fila', ja: '行列' },

      // 値段と支払い
      { it: "quant'è?", ja: 'おいくらですか' },
      { it: 'quanto viene?', ja: '合計いくらですか' },
      { it: 'il prezzo', ja: '値段' },
      { it: 'è caro', ja: '高い' },
      { it: 'è economico', ja: '安い' },
      { it: 'lo sconto', ja: '割引' },
      { it: 'i saldi', ja: 'セール', note: '夏と冬に時期が決まっている' },
      { it: "l'offerta", ja: '特売' },
      { it: 'gratis', ja: '無料' },
      { it: 'pagare', ja: '支払う' },
      { it: 'in contanti', ja: '現金で' },
      { it: 'con la carta', ja: 'カードで' },
      { it: 'il resto', ja: 'おつり' },
      { it: 'la ricevuta', ja: '領収書' },
      { it: 'il portafoglio', ja: '財布' },
      { it: 'i soldi', ja: 'お金' },
      { it: "l'euro", ja: 'ユーロ' },
      { it: 'il centesimo', ja: 'セント' },

      // やりとり
      { it: 'posso provare?', ja: '試着できますか' },
      { it: 'provare', ja: '試す' },
      { it: 'lo prendo', ja: 'これにします' },
      { it: 'sto solo guardando', ja: '見ているだけです' },
      { it: 'avete?', ja: 'ありますか' },
      { it: 'un altro colore', ja: '別の色' },
      { it: 'troppo grande', ja: '大きすぎる' },
      { it: 'troppo piccolo', ja: '小さすぎる' },
      { it: 'la taglia', ja: 'サイズ（服）' },
      { it: 'il numero', ja: 'サイズ（靴）' },
      { it: 'è aperto', ja: '開いている' },
      { it: 'è chiuso', ja: '閉まっている' },
      { it: "l'orario di apertura", ja: '営業時間' },
      { it: 'il regalo', ja: 'プレゼント' },
      { it: 'incartare', ja: '包装する' },

      // 色
      { it: 'il colore', ja: '色' },
      { it: 'rosso', ja: '赤' },
      { it: 'blu', ja: '青' },
      { it: 'verde', ja: '緑' },
      { it: 'giallo', ja: '黄' },
      { it: 'nero', ja: '黒' },
      { it: 'bianco', ja: '白' },
      { it: 'grigio', ja: '灰色' },
      { it: 'marrone', ja: '茶色' },

      // 服と持ちもの
      { it: 'la maglietta', ja: 'Tシャツ' },
      { it: 'la camicia', ja: 'シャツ' },
      { it: 'i pantaloni', ja: 'ズボン' },
      { it: 'la gonna', ja: 'スカート' },
      { it: 'il vestito', ja: 'ワンピース' },
      { it: 'la giacca', ja: 'ジャケット' },
      { it: 'il cappotto', ja: 'コート' },
      { it: 'le scarpe', ja: '靴' },
      { it: 'i calzini', ja: '靴下' },
      { it: 'la borsa', ja: 'バッグ' },
      { it: 'il cappello', ja: '帽子' },
      { it: 'gli occhiali', ja: 'めがね' },
    ],
  },

  {
    id: 'famiglia',
    ja: '家族',
    hint: 'la sorella / i nonni',
    entries: [
      // 近い家族
      { it: 'la famiglia', ja: '家族' },
      { it: 'i genitori', ja: '両親' },
      { it: 'il padre', ja: '父' },
      { it: 'la madre', ja: '母' },
      { it: 'il papà', ja: 'パパ' },
      { it: 'la mamma', ja: 'ママ' },
      { it: 'il figlio', ja: '息子' },
      { it: 'la figlia', ja: '娘' },
      { it: 'i figli', ja: '子どもたち', note: '男女が混ざれば男性形' },
      { it: 'il figlio unico', ja: '一人っ子' },
      { it: 'il fratello', ja: '兄弟' },
      { it: 'la sorella', ja: '姉妹' },
      { it: 'il fratello maggiore', ja: '兄' },
      { it: 'il fratello minore', ja: '弟' },
      { it: 'la sorella maggiore', ja: '姉' },
      { it: 'la sorella minore', ja: '妹' },

      // 親戚
      { it: 'il nonno', ja: '祖父' },
      { it: 'la nonna', ja: '祖母' },
      { it: 'i nonni', ja: '祖父母' },
      { it: 'lo zio', ja: 'おじ' },
      { it: 'la zia', ja: 'おば' },
      { it: 'il cugino', ja: 'いとこ（男）' },
      { it: 'la cugina', ja: 'いとこ（女）' },
      { it: 'il nipote', ja: '孫、甥', note: '孫と甥の両方を指す' },
      { it: 'la nipote', ja: '孫娘、姪' },
      { it: 'il parente', ja: '親戚' },

      // 結婚まわり
      { it: 'il marito', ja: '夫' },
      { it: 'la moglie', ja: '妻' },
      { it: 'il fidanzato', ja: '恋人（男）' },
      { it: 'la fidanzata', ja: '恋人（女）' },
      { it: 'sposarsi', ja: '結婚する' },
      { it: 'il matrimonio', ja: '結婚式' },
      { it: 'sposato', ja: '既婚の' },
      { it: 'single', ja: '独身の' },
      { it: 'divorziato', ja: '離婚した' },
      { it: 'il suocero', ja: '義父' },
      { it: 'la suocera', ja: '義母' },
      { it: 'i suoceri', ja: '義理の両親' },
      { it: 'il genero', ja: '娘の夫' },
      { it: 'la nuora', ja: '息子の妻' },
      { it: 'il cognato', ja: '義理の兄弟' },
      { it: 'la cognata', ja: '義理の姉妹' },

      // 人を指す言葉
      { it: 'il bambino', ja: '男の子' },
      { it: 'la bambina', ja: '女の子' },
      { it: 'il ragazzo', ja: '若者（男）' },
      { it: 'la ragazza', ja: '若者（女）' },
      { it: "l'uomo", ja: '男の人' },
      { it: 'la donna', ja: '女の人' },
      { it: 'il signore', ja: '男性（敬称）' },
      { it: 'la signora', ja: '女性（敬称）' },
      { it: "l'amico", ja: '友だち（男）' },
      { it: "l'amica", ja: '友だち（女）' },
      { it: 'il vicino', ja: '隣人' },

      // たずねる
      { it: 'quanti anni hai?', ja: '何歳ですか' },
      { it: "ho trent'anni", ja: '30歳です' },
      { it: 'sei sposato?', ja: '結婚してますか' },
      { it: 'hai figli?', ja: '子どもはいますか' },
      { it: 'hai fratelli?', ja: '兄弟はいますか' },
      { it: 'abito con', ja: '〜と住んでいます' },
      { it: 'il nome', ja: '名前' },
      { it: 'il cognome', ja: '名字' },
      { it: 'il compleanno', ja: '誕生日' },
      { it: 'la casa', ja: '家' },

      // 人を説明する
      { it: 'maggiore', ja: '年上の' },
      { it: 'minore', ja: '年下の' },
      { it: 'giovane', ja: '若い' },
      { it: 'anziano', ja: '年配の' },
      { it: 'simpatico', ja: '感じがいい' },
      { it: 'gentile', ja: '親切な' },
      { it: 'alto', ja: '背が高い' },
      { it: 'basso', ja: '背が低い' },
      { it: 'assomigliare', ja: '似ている' },
      { it: 'il gatto', ja: '猫' },
      { it: 'il cane', ja: '犬' },
    ],
  },

  {
    id: 'tempo',
    ja: '天気・季節',
    hint: "piove / l'estate",
    entries: [
      // 天気をたずねる
      { it: 'il tempo', ja: '天気', note: '「時間」の意味もある' },
      { it: 'che tempo fa?', ja: '天気はどう？' },
      { it: 'fa bello', ja: '天気がいい' },
      { it: 'fa brutto', ja: '天気が悪い' },
      { it: 'la previsione', ja: '天気予報' },

      // 空のようす
      { it: 'il cielo', ja: '空' },
      { it: 'il sole', ja: '太陽' },
      { it: "c'è il sole", ja: '晴れている' },
      { it: 'sereno', ja: '快晴の' },
      { it: 'la nuvola', ja: '雲' },
      { it: 'è nuvoloso', ja: '曇っている' },
      { it: 'coperto', ja: '曇天の' },
      { it: "l'arcobaleno", ja: '虹' },

      // 降る・吹く
      { it: 'la pioggia', ja: '雨' },
      { it: 'piove', ja: '雨が降っている' },
      { it: 'la neve', ja: '雪' },
      { it: 'nevica', ja: '雪が降っている' },
      { it: 'il vento', ja: '風' },
      { it: 'tira vento', ja: '風が吹いている' },
      { it: 'la nebbia', ja: '霧' },
      { it: 'il temporale', ja: '雷雨' },
      { it: 'il tuono', ja: '雷の音' },
      { it: 'il fulmine', ja: '稲妻' },
      { it: 'la grandine', ja: 'ひょう' },
      { it: 'il ghiaccio', ja: '氷' },
      { it: "l'ombrello", ja: '傘' },
      { it: 'bagnato', ja: '濡れた' },
      { it: 'asciutto', ja: '乾いた' },

      // 暑さ寒さ
      { it: 'fa caldo', ja: '暑い' },
      { it: 'fa freddo', ja: '寒い' },
      { it: 'fa fresco', ja: '涼しい' },
      { it: 'è umido', ja: '湿気がある' },
      { it: 'afoso', ja: '蒸し暑い' },
      { it: 'il caldo', ja: '暑さ' },
      { it: 'il freddo', ja: '寒さ' },
      { it: "l'afa", ja: '蒸し暑さ' },
      { it: 'il clima', ja: '気候' },
      { it: 'la temperatura', ja: '気温' },
      { it: 'i gradi', ja: '度' },
      { it: 'sopra zero', ja: '氷点上' },
      { it: 'sotto zero', ja: '氷点下' },

      // 季節
      { it: 'la stagione', ja: '季節' },
      { it: 'la primavera', ja: '春' },
      { it: "l'estate", ja: '夏' },
      { it: "l'autunno", ja: '秋' },
      { it: "l'inverno", ja: '冬' },
      { it: 'in primavera', ja: '春に' },
      { it: "d'estate", ja: '夏に' },
      { it: 'la fioritura', ja: '開花' },
      { it: 'le foglie', ja: '葉' },
      { it: 'il raccolto', ja: '収穫' },

      // いつ
      { it: "l'anno", ja: '年' },
      { it: 'il mese', ja: '暦の月' },
      { it: 'la settimana', ja: '週' },
      { it: 'il giorno', ja: '日' },
      { it: 'oggi', ja: '今日' },
      { it: 'domani', ja: '明日' },
      { it: 'ieri', ja: '昨日' },
      { it: 'dopodomani', ja: 'あさって' },
      { it: "l'altro ieri", ja: 'おととい' },
      { it: 'la mattina', ja: '朝' },
      { it: 'il pomeriggio', ja: '午後' },
      { it: 'la sera', ja: '夕方' },
      { it: 'la notte', ja: '夜' },
      { it: 'stamattina', ja: '今朝' },
      { it: 'stasera', ja: '今晩' },
      { it: 'adesso', ja: '今' },
      { it: 'presto', ja: '早く' },
      { it: 'tardi', ja: '遅く' },
      { it: 'sempre', ja: 'いつも' },
      { it: 'spesso', ja: 'よく' },
      { it: 'a volte', ja: 'ときどき' },
      { it: 'mai', ja: '決して〜ない' },
    ],
  },

  {
    id: 'salute',
    ja: '体調',
    hint: 'ho mal di testa / la febbre',
    entries: [
      // 調子を伝える
      { it: 'la salute', ja: '健康' },
      { it: 'come ti senti?', ja: '気分はどう？' },
      { it: 'non mi sento bene', ja: '気分が悪い' },
      { it: 'sto male', ja: '具合が悪い' },
      { it: 'sono stanco', ja: '疲れた' },
      { it: 'fa male', ja: '痛む' },
      { it: 'mi fa male qui', ja: 'ここが痛い' },
      { it: 'da quanto tempo?', ja: 'いつからですか', note: '医者に聞かれる決まり文句' },

      // 症状
      { it: 'ho mal di testa', ja: '頭が痛い', note: 'mal di + 部位 で「〜が痛い」' },
      { it: 'ho mal di stomaco', ja: '胃が痛い' },
      { it: 'ho mal di gola', ja: 'のどが痛い' },
      { it: 'ho mal di denti', ja: '歯が痛い' },
      { it: 'ho mal di schiena', ja: '腰が痛い' },
      { it: 'il dolore', ja: '痛み' },
      { it: 'la febbre', ja: '熱' },
      { it: 'il raffreddore', ja: '風邪' },
      { it: "l'influenza", ja: 'インフルエンザ' },
      { it: 'la tosse', ja: 'せき' },
      { it: 'il naso chiuso', ja: '鼻づまり' },
      { it: 'lo starnuto', ja: 'くしゃみ' },
      { it: "l'allergia", ja: 'アレルギー' },
      { it: 'la nausea', ja: '吐き気' },
      { it: 'la diarrea', ja: '下痢' },
      { it: 'la stitichezza', ja: '便秘' },
      { it: 'la vertigine', ja: 'めまい' },
      { it: 'la stanchezza', ja: '疲れ' },
      { it: 'il sonno', ja: '眠気' },
      { it: 'la ferita', ja: '傷' },
      { it: 'rompersi', ja: '骨折する' },

      // 医者と薬
      { it: 'il medico', ja: '医者' },
      { it: 'il dentista', ja: '歯医者' },
      { it: "l'ospedale", ja: '病院' },
      { it: 'il pronto soccorso', ja: '救急外来' },
      { it: "l'ambulanza", ja: '救急車' },
      { it: 'la visita', ja: '診察' },
      { it: "l'analisi", ja: '検査' },
      { it: 'la ricetta', ja: '処方箋' },
      { it: 'la medicina', ja: '薬' },
      { it: 'la pastiglia', ja: '錠剤' },
      { it: 'lo sciroppo', ja: 'シロップ薬' },
      { it: 'il cerotto', ja: 'ばんそうこう' },
      { it: 'la puntura', ja: '注射' },
      { it: "l'assicurazione", ja: '保険' },
      { it: 'il riposo', ja: '休養' },
      { it: 'guarire', ja: '治る' },
      { it: 'respirare', ja: '呼吸する' },

      // 体の部位
      { it: 'il corpo', ja: '体' },
      { it: 'la testa', ja: '頭' },
      { it: 'il viso', ja: '顔' },
      { it: "l'occhio", ja: '目' },
      { it: "l'orecchio", ja: '耳' },
      { it: 'il naso', ja: '鼻' },
      { it: 'la bocca', ja: '口' },
      { it: 'il dente', ja: '歯' },
      { it: 'la lingua', ja: '舌' },
      { it: 'il collo', ja: '首' },
      { it: 'la spalla', ja: '肩' },
      { it: 'il braccio', ja: '腕' },
      { it: 'la mano', ja: '手', note: '女性名詞。複数は le mani' },
      { it: 'il dito', ja: '指' },
      { it: 'il petto', ja: '胸' },
      { it: 'la pancia', ja: 'お腹' },
      { it: 'la schiena', ja: '背中' },
      { it: 'la gamba', ja: '脚' },
      { it: 'il ginocchio', ja: 'ひざ' },
      { it: 'il piede', ja: '足' },
      { it: 'il cuore', ja: '心臓' },
      { it: 'il sangue', ja: '血' },
      { it: "l'osso", ja: '骨' },
      { it: 'la pelle', ja: '肌' },
      { it: 'i capelli', ja: '髪' },
    ],
  },

  {
    id: 'viaggio',
    ja: '旅行',
    hint: 'la prenotazione / il museo',
    entries: [
      // 旅そのもの
      { it: 'il viaggio', ja: '旅行' },
      { it: 'viaggiare', ja: '旅行する' },
      { it: 'la vacanza', ja: '休暇' },
      { it: 'il turista', ja: '観光客' },
      { it: 'il rientro', ja: '帰り' },
      { it: 'il fuso orario', ja: '時差' },
      { it: 'la stagione alta', ja: 'ハイシーズン' },
      { it: 'la stagione bassa', ja: 'オフシーズン' },

      // 宿
      { it: "l'albergo", ja: 'ホテル' },
      { it: "l'ostello", ja: 'ユースホステル' },
      { it: "l'agriturismo", ja: '農家民宿', note: '田舎の農園に泊まる形式' },
      { it: 'la prenotazione', ja: '予約' },
      { it: 'la reception', ja: 'フロント' },
      { it: 'la camera singola', ja: 'シングルルーム' },
      { it: 'la camera doppia', ja: 'ツインルーム' },
      { it: 'la chiave', ja: '鍵' },
      { it: 'il piano', ja: '階' },
      { it: 'la colazione inclusa', ja: '朝食つき' },
      { it: 'il check in', ja: 'チェックイン' },
      { it: 'il documento', ja: '身分証', note: 'ホテルでは必ず求められる' },
      { it: 'la carta di credito', ja: 'クレジットカード' },

      // 見どころ
      { it: 'il museo', ja: '美術館' },
      { it: 'la mostra', ja: '展覧会' },
      { it: "il biglietto d'ingresso", ja: '入場券' },
      { it: "l'ingresso", ja: '入場' },
      { it: 'gratuito', ja: '無料の' },
      { it: 'la guida', ja: 'ガイド' },
      { it: "l'audioguida", ja: '音声ガイド' },
      { it: 'il monumento', ja: '記念建造物' },
      { it: 'la chiesa', ja: '教会' },
      { it: 'il duomo', ja: '大聖堂' },
      { it: 'la basilica', ja: 'バジリカ' },
      { it: 'il castello', ja: '城' },
      { it: 'la torre', ja: '塔' },
      { it: 'le rovine', ja: '遺跡' },
      { it: 'la fontana', ja: '噴水' },
      { it: 'il giardino', ja: '庭園' },
      { it: 'il panorama', ja: '眺め' },
      { it: 'aperto al pubblico', ja: '一般公開' },

      // 土地
      { it: 'la spiaggia', ja: 'ビーチ' },
      { it: 'il mare', ja: '海' },
      { it: 'la montagna', ja: '山' },
      { it: 'il lago', ja: '湖' },
      { it: 'il fiume', ja: '川' },
      { it: "l'isola", ja: '島' },
      { it: 'la campagna', ja: '田舎' },
      { it: 'il paese', ja: '村' },
      { it: 'la città', ja: '街' },
      { it: 'la regione', ja: '州' },

      // 買って帰る
      { it: 'il souvenir', ja: 'おみやげ' },
      { it: 'la cartolina', ja: '絵はがき' },
      { it: 'il francobollo', ja: '切手' },
      { it: 'la foto', ja: '写真' },
      { it: 'fare una foto', ja: '写真を撮る' },
      { it: 'il ricordo', ja: '思い出' },

      // 相談する
      { it: 'il consiglio', ja: 'おすすめ' },
      { it: 'che cosa mi consiglia?', ja: '何がおすすめですか' },
      { it: 'vale la pena', ja: '行く価値がある' },
      { it: 'affollato', ja: '混んでいる' },
      { it: 'tranquillo', ja: '静かな' },

      // 困ったとき
      { it: 'ho perso', ja: 'なくしました' },
      { it: "l'oggetto smarrito", ja: '遺失物' },
      { it: 'il ladro', ja: '泥棒' },
      { it: 'il furto', ja: '盗難' },
      { it: 'la polizia', ja: '警察' },
      { it: "l'ambasciata", ja: '大使館' },
      { it: 'aiuto!', ja: '助けて！' },
      { it: 'la valuta', ja: '通貨' },
      { it: 'il cambio', ja: '両替' },
      { it: 'il bancomat', ja: 'ATM' },
    ],
  },

  {
    id: 'lavoro',
    ja: '仕事',
    hint: 'la riunione / la scadenza',
    entries: [
      // 職場
      { it: 'il lavoro', ja: '仕事' },
      { it: 'lavorare', ja: '働く' },
      { it: "l'ufficio", ja: 'オフィス' },
      { it: "l'azienda", ja: '会社' },
      { it: 'la ditta', ja: '企業' },
      { it: 'il reparto', ja: '部署' },
      { it: 'la scrivania', ja: '机' },
      { it: 'la sedia', ja: 'いす' },
      { it: 'il capo', ja: '上司' },
      { it: 'il direttore', ja: '部長' },
      { it: 'il dipendente', ja: '従業員' },
      { it: 'il collega', ja: '同僚' },
      { it: 'il cliente', ja: '顧客' },
      { it: 'il capo progetto', ja: 'プロジェクト責任者' },

      // 打ち合わせ
      { it: 'la riunione', ja: '会議' },
      { it: "l'incontro", ja: '打ち合わせ' },
      { it: 'sono in riunione', ja: '会議中です' },
      { it: 'fissare un incontro', ja: '打ち合わせを設定する' },
      { it: 'la presentazione', ja: 'プレゼン' },
      { it: 'la relazione', ja: '報告書' },
      { it: 'la telefonata', ja: '電話（一本の）' },

      // 段取り
      { it: 'il progetto', ja: 'プロジェクト' },
      { it: 'la scadenza', ja: '締め切り' },
      { it: "l'obiettivo", ja: '目標' },
      { it: 'la mansione', ja: '職務' },
      { it: 'il preventivo', ja: '見積もり' },
      { it: 'la fattura', ja: '請求書' },
      { it: 'il bonifico', ja: '銀行振込' },
      { it: 'la tassa', ja: '税金' },
      { it: 'la partita IVA', ja: '個人事業主番号', note: 'フリーランスに必要な登録番号' },

      // 条件
      { it: 'il contratto', ja: '契約' },
      { it: 'lo stipendio', ja: '給料' },
      { it: 'lo stipendio netto', ja: '手取り' },
      { it: "l'orario di lavoro", ja: '勤務時間' },
      { it: 'lo straordinario', ja: '残業' },
      { it: 'le ferie', ja: '有給休暇' },
      { it: 'il congedo', ja: '休職' },
      { it: 'la pausa', ja: '休憩' },
      { it: 'la pausa pranzo', ja: '昼休み' },
      { it: 'il posto fisso', ja: '正社員の職' },
      { it: 'il part time', ja: 'パートタイム' },
      { it: 'il sindacato', ja: '労働組合' },
      { it: 'la pensione', ja: '年金' },

      // 出入り
      { it: 'il colloquio', ja: '面接' },
      { it: 'il curriculum', ja: '履歴書' },
      { it: 'assumere', ja: '採用する' },
      { it: 'licenziare', ja: '解雇する' },
      { it: 'dimettersi', ja: '辞職する' },
      { it: 'la carriera', ja: 'キャリア' },
      { it: "l'esperienza", ja: '経験' },
      { it: 'la formazione', ja: '研修' },
      { it: 'il tirocinio', ja: 'インターン' },

      // 職業
      { it: "l'impiegato", ja: '会社員' },
      { it: 'il libero professionista', ja: 'フリーランス' },
      { it: "l'operaio", ja: '工員' },
      { it: 'il commercialista', ja: '会計士' },
      { it: "l'avvocato", ja: '弁護士' },
      { it: "l'ingegnere", ja: 'エンジニア' },
      { it: "l'insegnante", ja: '教師' },
      { it: 'il professore', ja: '教授' },
      { it: 'lo studente', ja: '学生' },
      { it: 'il cuoco', ja: '料理人' },
      { it: 'il negoziante', ja: '商店主' },
      { it: "l'artigiano", ja: '職人' },
      { it: 'il contadino', ja: '農家' },
      { it: "l'autista", ja: '運転手' },
      { it: 'la segretaria', ja: '秘書' },
      { it: 'il giornalista', ja: '記者' },
      { it: "l'infermiere", ja: '看護師' },
    ],
  },

  {
    id: 'informatica',
    ja: 'IT',
    hint: 'la password / scaricare',
    entries: [
      // 機械
      { it: 'il computer', ja: 'パソコン' },
      { it: 'il portatile', ja: 'ノートパソコン' },
      { it: 'lo schermo', ja: '画面' },
      { it: 'la tastiera', ja: 'キーボード' },
      { it: 'il mouse', ja: 'マウス' },
      { it: 'la stampante', ja: 'プリンター' },
      { it: 'il cavo', ja: 'ケーブル' },
      { it: 'la batteria', ja: 'バッテリー' },
      { it: 'il caricabatterie', ja: '充電器' },
      { it: 'la presa', ja: 'コンセント' },
      { it: 'il telefonino', ja: '携帯電話' },
      { it: 'lo smartphone', ja: 'スマホ' },
      { it: 'il tablet', ja: 'タブレット' },
      { it: 'la memoria', ja: 'メモリ' },
      { it: 'il disco', ja: 'ディスク' },

      // 操作
      { it: 'accendere', ja: '電源を入れる' },
      { it: 'spegnere', ja: '電源を切る' },
      { it: 'riavviare', ja: '再起動する' },
      { it: 'aprire', ja: '開く' },
      { it: 'chiudere', ja: '閉じる' },
      { it: 'salvare', ja: '保存する' },
      { it: 'cancellare', ja: '削除する' },
      { it: 'copiare', ja: 'コピーする' },
      { it: 'incollare', ja: '貼り付ける' },
      { it: 'scaricare', ja: 'ダウンロードする' },
      { it: 'caricare', ja: 'アップロードする' },
      { it: 'installare', ja: 'インストールする' },
      { it: 'aggiornare', ja: '更新する' },
      { it: 'collegare', ja: '接続する' },
      { it: 'condividere', ja: '共有する' },
      { it: 'cercare', ja: '検索する' },

      // ソフト
      { it: "l'app", ja: 'アプリ' },
      { it: 'il programma', ja: 'プログラム' },
      { it: 'il software', ja: 'ソフトウェア' },
      { it: 'il file', ja: 'ファイル' },
      { it: 'la cartella', ja: 'フォルダ' },
      { it: 'il codice', ja: 'コード' },
      { it: 'il bug', ja: 'バグ' },
      { it: "l'errore", ja: 'エラー' },
      { it: 'non funziona', ja: '動かない' },
      { it: 'si è bloccato', ja: 'フリーズした' },
      { it: 'lo sviluppo', ja: '開発' },
      { it: 'il programmatore', ja: 'プログラマー' },

      // ネット
      { it: 'internet', ja: 'インターネット' },
      { it: 'la connessione', ja: '接続' },
      { it: 'il wifi', ja: '無線LAN' },
      { it: 'il sito', ja: 'サイト' },
      { it: 'la pagina', ja: 'ページ' },
      { it: 'il link', ja: 'リンク' },
      { it: 'il motore di ricerca', ja: '検索エンジン' },
      { it: 'il cloud', ja: 'クラウド' },
      { it: 'il backup', ja: 'バックアップ' },
      { it: 'i dati', ja: 'データ' },
      { it: "l'intelligenza artificiale", ja: '人工知能' },

      // アカウント
      { it: "l'utente", ja: 'ユーザー' },
      { it: "l'account", ja: 'アカウント' },
      { it: 'la password', ja: 'パスワード' },
      { it: 'accedere', ja: 'ログインする' },
      { it: 'registrarsi', ja: '登録する' },
      { it: 'la sicurezza', ja: 'セキュリティ' },
      { it: 'il virus', ja: 'ウイルス' },
      { it: 'la privacy', ja: 'プライバシー' },

      // やりとり
      { it: 'la mail', ja: 'メール' },
      { it: 'inviare', ja: '送信する' },
      { it: 'rispondere', ja: '返信する' },
      { it: 'allegare', ja: '添付する' },
      { it: "l'allegato", ja: '添付ファイル' },
      { it: 'il messaggio', ja: 'メッセージ' },
      { it: 'la chiamata', ja: '通話' },
      { it: 'la videochiamata', ja: 'ビデオ通話' },
      { it: 'il gruppo', ja: 'グループ' },
      { it: 'lo schermo condiviso', ja: '画面共有' },
    ],
  },

  {
    id: 'cultura',
    ja: 'イタリア文化',
    hint: "l'aperitivo / il Rinascimento",
    entries: [
      // 美術
      { it: 'la cultura', ja: '文化' },
      { it: "l'arte", ja: '芸術' },
      { it: 'il quadro', ja: '絵画作品' },
      { it: 'la pittura', ja: '絵画芸術' },
      { it: 'la scultura', ja: '彫刻' },
      { it: "l'affresco", ja: 'フレスコ画' },
      { it: "l'artista", ja: '芸術家' },
      { it: 'il capolavoro', ja: '傑作' },
      { it: 'la galleria', ja: '画廊' },
      { it: 'il Rinascimento', ja: 'ルネサンス' },
      { it: 'il Barocco', ja: 'バロック' },
      { it: 'il patrimonio', ja: '遺産' },

      // 音楽と舞台
      { it: "l'opera", ja: 'オペラ' },
      { it: 'la lirica', ja: 'オペラ音楽' },
      { it: 'il teatro', ja: '劇場' },
      { it: 'il tenore', ja: 'テノール' },
      { it: 'il soprano', ja: 'ソプラノ' },
      { it: 'il maestro', ja: '巨匠' },
      { it: "l'orchestra", ja: 'オーケストラ' },
      { it: 'il concerto', ja: 'コンサート' },
      { it: 'la canzone', ja: '歌' },
      { it: 'il cantante', ja: '歌手' },
      { it: 'il festival', ja: '音楽祭' },
      { it: 'Sanremo', ja: 'サンレモ音楽祭', note: '毎年2月の歌の祭典' },

      // 映画と本
      { it: 'il cinema', ja: '映画館' },
      { it: 'il film', ja: '映画' },
      { it: 'il regista', ja: '映画監督' },
      { it: "l'attore", ja: '俳優' },
      { it: 'la letteratura', ja: '文学' },
      { it: 'il romanzo', ja: '小説' },
      { it: 'il poeta', ja: '詩人' },
      { it: 'Dante', ja: 'ダンテ' },
      { it: 'la Divina Commedia', ja: '神曲' },
      { it: 'il quotidiano', ja: '日刊紙' },

      // 歴史と宗教
      { it: 'la storia', ja: '歴史' },
      { it: "l'impero romano", ja: 'ローマ帝国' },
      { it: 'il Colosseo', ja: 'コロッセオ' },
      { it: 'la Repubblica', ja: '共和国' },
      { it: 'il Papa', ja: '教皇' },
      { it: 'il Vaticano', ja: 'バチカン' },
      { it: 'la messa', ja: 'ミサ' },
      { it: 'il santo', ja: '聖人' },
      { it: 'il patrono', ja: '守護聖人', note: '町ごとに守護聖人の日が祝日になる' },
      { it: 'il campanile', ja: '鐘楼' },

      // 祭りと休み
      { it: 'la sagra', ja: '村祭り', note: '食べ物が主役の地元の祭り' },
      { it: 'il carnevale', ja: 'カーニバル' },
      { it: 'la Pasqua', ja: '復活祭' },
      { it: 'il Ferragosto', ja: '八月十五日の祝日', note: '街じゅうが閉まる' },
      { it: 'il giorno festivo', ja: '祝日' },
      { it: 'il palio', ja: 'パリオ', note: 'シエナなどで行われる伝統の競馬' },

      // 暮らしの習慣
      { it: "l'aperitivo", ja: 'アペリティーボ', note: '夕食前の一杯とつまみ' },
      { it: 'la passeggiata', ja: '夕方の散歩', note: '街を歩いて人に会う習慣' },
      { it: 'la chiusura pomeridiana', ja: '昼の休業' },
      { it: 'la tradizione', ja: '伝統' },
      { it: 'il dialetto', ja: '方言' },
      { it: 'il gesto', ja: '身ぶり', note: '手の動きも会話の一部' },
      { it: 'il campanilismo', ja: '郷土愛', note: '自分の町がいちばんという感覚' },
      { it: 'il centro storico', ja: '旧市街' },

      // イタリアらしいもの
      { it: 'la moda', ja: 'ファッション' },
      { it: 'il design', ja: 'デザイン' },
      { it: 'il made in Italy', ja: 'メイドインイタリー' },
      { it: 'la dolce vita', ja: '甘い生活' },
      { it: 'il bel paese', ja: '美しい国', note: 'イタリア自身を指す言い方' },
      { it: 'la vespa', ja: 'ベスパ' },
      { it: 'la Ferrari', ja: 'フェラーリ' },
      { it: 'la lingua italiana', ja: 'イタリア語' },
      { it: "l'accento", ja: 'アクセント' },
    ],
  },

  {
    id: 'calcio',
    ja: 'カルチョ',
    hint: 'il rigore / Forza!',
    entries: [
      // 基本
      { it: 'il calcio', ja: 'サッカー' },
      { it: 'la partita', ja: '試合' },
      { it: 'la squadra', ja: 'チーム' },
      { it: 'il tifoso', ja: 'サポーター' },
      { it: 'tifare', ja: '応援する', note: 'tifare per + チーム名' },
      { it: 'il gol', ja: 'ゴール' },
      { it: 'segnare', ja: '得点する' },
      { it: 'lo stadio', ja: 'スタジアム' },
      { it: 'il derby', ja: 'ダービー' },

      // 人
      { it: 'il giocatore', ja: '選手' },
      { it: 'il portiere', ja: 'ゴールキーパー' },
      { it: 'il difensore', ja: 'ディフェンダー' },
      { it: 'il centrocampista', ja: 'ミッドフィルダー' },
      { it: "l'attaccante", ja: 'フォワード' },
      { it: 'il capitano', ja: 'キャプテン' },
      { it: 'la riserva', ja: '控え選手' },
      { it: 'il bomber', ja: '点取り屋', note: '決定力のある FW を指す口語' },
      { it: "l'allenatore", ja: '監督' },
      { it: "l'arbitro", ja: '主審' },
      { it: 'il guardalinee', ja: '線審', note: '正式には assistente arbitrale' },
      { it: 'la Nazionale', ja: '代表チーム', note: 'イタリア代表の愛称は gli Azzurri' },
      { it: 'la panchina', ja: 'ベンチ' },

      // プレー
      { it: 'il passaggio', ja: 'パス' },
      { it: 'il tiro', ja: 'シュート' },
      { it: 'il cross', ja: 'クロス' },
      { it: 'il colpo di testa', ja: 'ヘディング' },
      { it: 'la rovesciata', ja: 'オーバーヘッドキック' },
      { it: 'il dribbling', ja: 'ドリブル' },
      { it: 'la parata', ja: 'セーブ', note: 'portiere がシュートを止めること' },
      { it: 'il contropiede', ja: 'カウンター' },
      { it: 'il possesso palla', ja: 'ボール支配率' },
      { it: 'il palo', ja: 'ゴールポスト' },
      { it: 'la traversa', ja: 'クロスバー' },
      { it: 'la rete', ja: 'ゴールネット', note: '実況では得点そのものも rete と言う' },
      { it: "l'autogol", ja: 'オウンゴール' },

      // 判定
      { it: 'il fallo', ja: 'ファウル' },
      { it: 'il rigore', ja: 'PK' },
      { it: "il calcio d'angolo", ja: 'コーナーキック' },
      { it: 'la punizione', ja: 'フリーキック' },
      { it: 'il fuorigioco', ja: 'オフサイド' },
      { it: 'il cartellino giallo', ja: 'イエローカード' },
      { it: 'il cartellino rosso', ja: 'レッドカード' },
      { it: "l'ammonizione", ja: '警告', note: 'カードそのものは cartellino' },
      { it: "l'espulsione", ja: '退場' },
      { it: 'il VAR', ja: 'ビデオ判定' },
      { it: 'il fischio', ja: 'ホイッスル' },

      // 試合の流れ
      { it: "il calcio d'inizio", ja: 'キックオフ' },
      { it: 'il primo tempo', ja: '前半' },
      { it: 'il secondo tempo', ja: '後半' },
      { it: 'il recupero', ja: 'アディショナルタイム' },
      { it: 'il tempo supplementare', ja: '延長戦' },
      { it: 'i rigori', ja: 'PK戦', note: '延長でも決まらないときの決着' },
      { it: "l'infortunio", ja: 'けが' },
      { it: 'la sostituzione', ja: '選手交代' },

      // 勝ち負けと順位
      { it: 'il pareggio', ja: '引き分け' },
      { it: 'la vittoria', ja: '勝利' },
      { it: 'la sconfitta', ja: '敗北' },
      { it: 'il campionato', ja: 'リーグ戦' },
      { it: 'la coppa', ja: 'カップ戦' },
      { it: 'la Serie A', ja: 'セリエA' },
      { it: 'lo scudetto', ja: 'リーグ優勝', note: '優勝チームが翌季つける盾の印' },
      { it: 'la retrocessione', ja: '降格' },
      { it: 'la promozione', ja: '昇格' },
      { it: 'il girone', ja: 'グループリーグ' },
      { it: 'la classifica', ja: '順位表' },
      { it: 'la trasferta', ja: 'アウェー' },
      { it: 'in casa', ja: 'ホームで' },
      { it: 'il punteggio', ja: 'スコア' },
      { it: 'i punti', ja: '勝ち点' },

      // スタジアムで
      { it: 'la curva', ja: 'ゴール裏', note: '熱心なサポーターが陣取る席' },
      { it: 'il coro', ja: 'チャント' },
      { it: 'lo striscione', ja: '横断幕' },
      { it: 'forza!', ja: 'がんばれ！' },
      { it: 'dai!', ja: 'いけ！、ほら！' },
      { it: 'che gol!', ja: 'なんてゴールだ！' },
    ],
  },
];

export const TOPIC_IDS = TOPICS.map((t) => t.id);

export const topicById = (id) => TOPICS.find((t) => t.id === id) ?? null;

/** エントリ数（設定画面の表示用） */
export const topicSize = (id) => topicById(id)?.entries.length ?? 0;
